### PR TITLE
950 coverage for calculation results and detailed break down page

### PR DESCRIPTION
**Pull request by swetaoza16**

### CODE REVIEW

**Comment by swetaoza16** [comment]
Screenshot from 2024-11-11 14-53-37

**Comment by swetaoza16** [comment]
Screenshot from 2024-11-11 14-54-50

**Comment by swetaoza16** [comment]
local run test report for all tests
Screenshot from 2024-11-11 15-20-13

**Comment by swetaoza16** [comment]
Screenshot from 2024-11-11 16-14-19

**Review by neelu-dwivedi — APPROVED** [review]

**Pull request merged**
